version: '3.7'

services:

  app:
    build: .
    image: app
    container_name: falcon
    ports:
      - 5001:5001
    command: gunicorn app.wsgi:api --bind 0.0.0.0:5001 --workers 2 --threads 4 --worker-class gthread --worker-tmp-dir /dev/shm
    env_file:
      - .env
    environment:
      - CELERY_BROKER
      - CELERY_BACKEND
    depends_on:
      - redis

  celery:
    image: app
    container_name: celery-worker1
    command: celery worker --app app.worker --concurrency 2 --loglevel INFO --events
    env_file:
      - .env
    environment:
      - CELERY_BROKER
      - CELERY_BACKEND
    depends_on:
      - app
      - redis

  monitor:
    image: app
    container_name: flower
    command: flower --app app.worker
    ports:
      - 5555:5555
    env_file:
      - .env
    environment:
      - CELERY_BROKER
      - CELERY_BACKEND
      - FLOWER_BROKER
    depends_on:
      - app
      - celery
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
