version: '3.7'

services:

  app:
    build: .
    image: falcon
    container_name: gunicorn-falcon
    ports:
      - 5001:5001
    command: gunicorn app.wsgi:api --bind 0.0.0.0:5001 --workers 4
    env_file:
      - .env
    environment:
      - CELERY_BROKER
      - CELERY_BACKEND
    depends_on:
      - redis

  worker1:
    image: async-app
    container_name: celery-worker1
    command: celery worker --app app.extensions.queue --concurrency 2 --loglevel INFO --events
    env_file:
      - .env
    environment:
      - CELERY_BROKER
      - CELERY_BACKEND
    depends_on:
      - app
      - redis

  worker2:
    image: async-app
    container_name: celery-worker2
    command: celery worker --app app.extensions.queue --concurrency 2 --loglevel INFO --events
    env_file:
      - .env
    environment:
      - CELERY_BROKER
      - CELERY_BACKEND
    depends_on:
      - app
      - redis

  monitor:
    image: async-app
    container_name: flower
    command: flower --app app.extensions.queue
    ports:
      - 5555:5555
    env_file:
      - .env
    environment:
      - CELERY_BROKER
      - CELERY_BACKEND
      - FLOWER_BROKER
    depends_on:
      - app
      - redis

  redis:
    image: redis:alpine
    container_name: redis
